INSERT INTO ingredientes (nome)
VALUES ("Pão"),
    ("Hamburguer"),
    ("Queijo"),
    ("Tomate"),
    ("Cebola"),
    ("Alface"),
    ("Ovo"),
    ("Bacon"),
    ("Ketchup"),
    ("Mostarda"),
    ("Salsicha"),
    ("Picles"),
    ("Frango"),
    ("Milho"),
    ("Ervilha"),
    ("Molho Especial");
INSERT INTO lanches (nome)
VALUES ("X-Burguer"),
    ("X-Salada"),
    ("X-Tudo"),
    ("X-Bacon"),
    ("Hot Dog"),
    ("X-Frangão");
INSERT INTO lanche_ingredientes (id_ingrediente, id_lanche)
VALUES (1, 1),
    (2, 1),
    (3, 1),
    (1, 2),
    (2, 2),
    (3, 2),
    (4, 2),
    (5, 2),
    (6, 2),
    (12, 2),
    (16, 2),
    (1, 3),
    (2, 3),
    (3, 3),
    (4, 3),
    (5, 3),
    (6, 3),
    (7, 3),
    (8, 3),
    (14, 3),
    (15, 3),
    (16, 3),
    (1, 4),
    (2, 4),
    (3, 4),
    (7, 4),
    (8, 4),
    (9, 4),
    (1, 5),
    (11, 5),
    (9, 5),
    (10, 5),
    (1, 6),
    (13, 6),
    (3, 6),
    (4, 6),
    (5, 6),
    (6, 6);
INSERT INTO pedidos (nome_cliente, rua, bairro, numero)
VALUES ("Percival", "Rua 1", "Bairro A", 1),
    ("Douglas", "Rua 2", "Bairro B", 5),
    ("Abelardo", "Rua 3", "Bairro C", 10),
    ("Nelson", "Rua 4", "Bairro D", 15),
    ("Pedro", "Rua 5", "Bairro E", 20),
    ("Gabriel", "Rua 6", "Bairro F", 33);
INSERT INTO lanche_pedido (id_lanche, id_pedido)
VALUES (1, 1),
    (2, 2),
    (3, 2),
    (4, 3),
    (5, 3),
    (6, 3),
    (1, 4),
    (2, 4),
    (3, 4),
    (4, 4),
    (1, 5),
    (2, 5),
    (4, 5),
    (5, 5),
    (6, 5),
    (1, 6),
    (4, 6);
INSERT INTO lanche_pedido_ingredientes_extras (id_lanche_pedido, id_ingrediente, remover)
VALUES (1, 8, 0),
    (10, 4, 0),
    (10, 5, 1),
    (5, 3, 0),
    (15, 16, 0),
    (2, 4, 1),
    (9, 14, 1),
    (9, 15, 1),
    (13, 7, 0),
    (14, 9, 0);

INSERT INTO usuario (username, password) VALUES ('admin', '12345678');
INSERT INTO usuario (username, password) VALUES ('marcos', '87654321');